### ISSUE TITLE
Grading for UASB

### ISSUE THREAD

**Issue by zacchen15** [AguaClara/UASB#20]
@caseyching13 @MikeZarecor @nataliemottl 

I understand our team is officially a research team but the work that we're doing involves a combination of design and research.  At the moment we're creating designs in Markdown files for a pilot scale UASB reactor and documenting the details in that format.  We're also in the process of writing a EPA P3 Phase II grant.

With that being said, I have a few questions on grading and the report template.  We discussed with @zam7 that we're most likely going to change the structure of the report template to fit our work.  My first question is would you like us to include all of our code for the UASB reactor size calculations, tube settler dimensions, etc copied and pasted into the report or can we link documents in our repo?  How specifically will our grading rubric for this report be followed since we're not exactly a pure research team?  

In addition, how much of our grant writing would you like us to report on in the report and how should we reference that work?

Thanks for your time

**Comment by nataliemottl** [comment]
Hi Zac! There are a couple options. 
1. Do a manual & a Fusion 360 drawing
2. Do a really in depth and well articulated manual that outlines your design process. 
3. Do a manual & write a memo on the EPA report that you are writing.

I don't think doing a research report will be of much value here so let's take that out of the calculation.

I think options 2 or 3 are the best options (with a combo of the two being ideal). In the manual, any value/parameter that you list as being part of your design should have a justification. I would prefer that you have all the code in one place with explanations as needed rather than linking to the repository. The manual should be the place where your design process is documented and could be easily repeated.

Please let me know which option you think is best then I will change your rubrics to reflect that choice ASAP! (also let me know if you have more questions)

**Comment by zacchen15** [comment]
Thanks for the quick response @nataliemottl !

One more question I have is what would the memo encompass?  

Thanks again!

**Comment by nataliemottl** [comment]
Memo would probably be an overview of the EPA report and how that connects to the team and the other work you are doing. (Or any equivalent that your team thinks would be important to be documented.)

Do you know which one you are doing? I would like to update your rubric ASAP so that you can submit for tomorrow!

**Comment by IanCullings** [comment]
@nataliemottl We're going to go with option 2 and focus completely on the manual.  Thanks for your help!

**Comment by nataliemottl** [comment]
Please see your updated rubric. Scroll down to where it says Manual 1 (3/9/18)

This should give you more guidance on your manual. Sorry about this late update, but please in the future try to give me more time to make adjustments like this. Let me know if you need an extension to meet the grading criteria!

**Comment by zacchen15** [comment]
@nataliemottl can you share the rubric with us?  

The only file we got from Mike earlier in the semester was this one:
https://docs.google.com/document/d/1hOzdhDAZsIMLzUwiyfz9zfyBqJBNtPfhgyxMB2lcnhE/edit?ts=5a7b5c53

**Comment by nataliemottl** [comment]
I just sent a view-only invite for your whole team to your grading folder!

**Comment by zacchen15** [comment]
Thanks a lot for all your help!
