### ISSUE TITLE
Influent Pipe Dimensions

### ISSUE THREAD

**Issue by ananya-gangadhar** [AguaClara/UASB#23]
Most of the literature we have read so far suggests an influent pipe diameter of 75-100mm in order to allow gas bubbles to escape, and an area of influence of 1-2 m^2. However, since our reactor is fairly small, a 100mm pipe seems excessive, especially since we will be having two. 
The texts also suggest attaching a nozzle at the bottom end of the pipe to constrict the diameter to about 45mm in order to prevent deposition. Taking this into account, would it be feasible to reduce our overall pipe diameter to about 50mm and have some sort of funnel structure at the top to provide a large enough surface area for trapped air to escape?

@zoemaisel @JenniferKJackson

**Comment by zacchen15** [comment]
Correct me if I'm wrong but a jet reverser is used to suspend flocs in a sed tank right?  I don't think that's what we're going for since the bed is supposed to be settled.  I think we'd like to have a less concentrated stream to ensure slower and better distribution rather than a concentrated stream to suspend any of our granules.

**Comment by zoemaisel** [comment]
I also do not think that we need a jet reverser because all we care about is that the flow will turn around to flow up but the exact way that we do that is not important (as long as it is evenly distributed). I think that v-shaped will do this as sufficiently as a u-shaped bottom.

We met today and talked about the criteria that the influent pipes need to meet:

- Allow for gas escape (but also prevent gas entrainment)
- Deliver flow below maximum velocity at outlet
- Meet minimum diameter constraints to prevent clogging
- Account for a length of pipe sufficient to allow for declogging head loss build up and normal head loss requirements

**Comment by JenniferKJackson** [comment]
![img-5760](https://user-images.githubusercontent.com/31327430/37616916-ca290b0a-2b87-11e8-977c-c58b0dabdc99.JPG)
