### ISSUE TITLE
Influent Pipe Design Queries (To Discuss with Zoe)

### ISSUE THREAD

**Issue by ananya-gangadhar** [AguaClara/UASB#26]
- Preferred pipe diameter around 50 mm. This is a little below the recommended value to prevent clogging along the pipe but is just enough to prevent deposition at the end, and provide necessary exit velocity of about 0.40 m/s.

- Speaking of, we're shooting for an exit velocity of 0.4 m/s for each influent pipe.

- We calculated the flow rate into the reactor to be around 40 ml/s, meaning 20 ml/s per influent pipe. However, this calculation assumes a constant flow rate. Is the UASB design going to have some sort of a holding tank to ensure continuous flow? If not, can we still make our design calculations assuming steady flow?

- While both of our main literature sources agree that the exit velocity of the pipe should be greater than 0.3 m/s, should we check for more sources to corroborate this value?
@zoemaisel @zacchen15 @JenniferKJackson

**Comment by zoemaisel** [comment]
- We are going to design some sort of head tank to try to provide continuous flow, so you can assume steady flow.
- I think that if the literature that you've come across is consistent in suggesting greater than 0.3 m/s, and we think we will achieve 0.4 m/s, then we should be alright. It can be something that we keep in mind because if we come upon another source that says something else, then we can do more research.
