### ISSUE TITLE
Make Full Fusion Model of UASB

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/UASB#79]
In preparation for meeting with Ed and Jose at the IAWWTF, we need to make a full model of the UASB system.  Each component of the UASB should be created separately in a folder within the design document, then combined into one assembly.

**Comment by IanCullings** [comment]
Hi @AlyciaStorch!  Awesome job with the first model of the UASB.  Below are a few comments on the design.  If possible it would be great if you could address them today so that we'll have this ready for our presentation tomorrow!

- [ ] Angle the balloon straight upwards with another pipe.
- [ ] Move the influent pipes coming out of the tank so that they are right in the middle of the tank, directly under the tipping bucket.  The distance between the two pipes is 2 inches
- [ ] I don't know if this is possible, but if would be awesome to simulate the sludge blanket by filling the reactor with some sort of brown substance up to the height of the sludge weir
- [ ] While it's great to have the base of the tank transparent, it makes basically invisible in the digital link.  Is there any sort of semi-transparent material we could use?
- [ ] One design we are considering has larger pipes exiting the influent tank which then connect to the normal 3" pipes.  Pipe diam for those larger pipes still needs to be calculated.  If you could play around with that and see what works, that would be awesome (add any information you get to this Github issue)

**Comment by AlyciaStorch** [comment]
I updated the fusion based on these comments. Ananya also showed me what the actual tank looks like and I began to edit the designs so that the top part that is currently like a dome would be more accurate. As I began to do this though I realized that it would require changing A LOT of things so I kept the dome because I did have limited time. I know you have your presentation and meeting tomorrow so I don't know if its something you'd like me to update next week but if so I can do that. Sorry I wasn't able to finish that in time!

**Comment by AlyciaStorch** [comment]
Also, turns out the animation is more complex than I thought because Fusion's animation features don't recognize joints and joint constraints (which I find strange because I would imagine a lot of people would need that). One option is to download their screencast software and then just animate the joint in the normal model workspace and take a screencast. I tried to do this but since fusion isn't working on my computer and I have been using my work computer which is a Cornell computer, I couldn't install the software.

Last thing, for the designs with the larger pipes coming out of the entrance tank, I looked on McMaster and it seemed that the only reducers they had where the smaller end was 3" was 4" to 3" so I made the larger pipes 4" in the design.

**Comment by IanCullings** [comment]
Thanks @AlyciaStorch!  For now don't worry about the animation, that's a pretty minor issue.

The next steps would be to keep updating the top section as you mentioned and work on another design for the alternate influent system where the tank is right above the reactor.  For both designs we need to consider a way to attach the influent tank to the reactor for stability, so if you want to brainstorm and make some initial models of those ideas that would be awesome!  We can discuss this further on Monday in person.

**Comment by IanCullings** [comment]
Completed!  This will need to be transferred to OnShape later in the semester
